import type { GetServerSideProps } from 'next/types';

import Head from 'next/head';

import Counter from '~/components/Counter';
import { prefetch } from '~/react-query/server/prefetch';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Redux */}
        <Counter />
      </main>
    </>
  );
};

export default HomePage;

const queryFn = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos');
  const data = await res.json();
  return data as any[];
};

export const getServerSideProps: GetServerSideProps = async () => {
  const dehydrate = prefetch({
    queryKey: ['example'],
    queryFn,
  });

  const dehydratedState = await dehydrate();

  return {
    props: {
      dehydratedState,
    },
  };
};
