import type { GetServerSideProps } from 'next/types';

import { Inter } from 'next/font/google';
import Head from 'next/head';

import { useQuery } from '@tanstack/react-query';

import Counter from '~/components/Counter';
import EmotionComponent from '~/components/EmotionComponent';
import { prefetch } from '~/react-query/server/prefetch';
import styles from '~/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { data } = useQuery(['example'], queryFn);

  console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* Emotion */}
        <EmotionComponent />

        {/* Redux */}
        <Counter />
      </main>
    </>
  );
}

const queryFn = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos');
  const data = await res.json();
  return data as any[];
};

export const getServerSideProps: GetServerSideProps = async () => {
  const dehydrate = prefetch({
    queryKey: ['example'],
    queryFn,
  });

  const dehydratedState = await dehydrate();

  return {
    props: {
      dehydratedState,
    },
  };
};
